# Generated by Django 6.0.4 on 2026-05-13 13:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_time', models.DateTimeField()),
                ('glucose_forecast', models.DecimalField(decimal_places=2, max_digits=5)),
                ('insulin_effect', models.DecimalField(decimal_places=5, max_digits=10)),
                ('carbs_utilized', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calculation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModelConstants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('value', models.DecimalField(decimal_places=10, max_digits=20)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'model_constants',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.roles')),
            ],
            options={
                'db_table': 'doctor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('birth_date', models.DateField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.roles')),
            ],
            options={
                'db_table': 'patient',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InsulinInjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=datetime.date.today)),
                ('start_time', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.patient')),
            ],
            options={
                'db_table': 'insulin_injection',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GlucoseMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_time', models.DateTimeField()),
                ('glucose_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.patient')),
            ],
            options={
                'db_table': 'glucose_measurement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FoodIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=datetime.date.today)),
                ('start_time', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('carbs_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.patient')),
            ],
            options={
                'db_table': 'food_intake',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DoctorPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.patient')),
            ],
            options={
                'db_table': 'doctor_patient',
                'managed': True,
                'unique_together': {('doctor', 'patient')},
            },
        ),
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(max_length=50)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('calculation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.calculation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.patient')),
            ],
            options={
                'db_table': 'charts',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='calculation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.patient'),
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(max_length=20)),
                ('action_type', models.CharField(max_length=100)),
                ('action_time', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.doctor')),
                ('doctor_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.doctorpatient')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.patient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_history',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PatientParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bioavailability', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('glucose_transfer_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('insulin_absorption_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('glucose_deactivation_distribution', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('glucose_deactivation_utilization', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('glucose_deactivation_liver', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('meal_absorption_time', models.IntegerField(blank=True, null=True)),
                ('glucose_distribution_volume', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('insulin_distribution_volume', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('insulin_absorption_time', models.IntegerField(blank=True, null=True)),
                ('insulin_distribution_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('insulin_absorption_coefficient', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('insulin_effect_on_glucose_liver', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('liver_glucose_production_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True)),
                ('glucose_consumption_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('based_on_constant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.modelconstants')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.patient')),
            ],
            options={
                'db_table': 'patient_parameters',
                'managed': True,
            },
        ),
    ]
